import Head from 'next/head';
import Navbar from '../components/Navbar'; // Importe o componente Navbar
import styles from '../styles/Home.module.css';
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>NextBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Adicione a barra de navegação aqui */}
      <Navbar />

      <div>Home</div>
    </div>
  );
}